### ISSUE TITLE
Incapable of running the project in 4.0-beta1, due to syntax changes.

### ISSUE THREAD

**Issue by derinasir** [ywmaa/Advanced-Movement-System-Godot#24]
Some global scope functions like are renamed in previous alpha snapshots (like `rad2deg` is `rad_to_deg` now).

**Comment by ywmaa** [comment]
I already updated the functions, this happened in alpha 15 as I remember.
did you clone/pull the latest commit ?

**Comment by ywmaa** [comment]
I tried cloning the repo and opening the project using method 2 from the readme and it works.

**Comment by ywmaa** [comment]
closing this issue as there isn't an answer or verifying that the issue exists.
