### ISSUE TITLE
Add images or short videos in README

### ISSUE THREAD

**Issue by SSebigo** [ywmaa/Advanced-Movement-System-Godot#25]
Some images or a short video in the README would help as promotional material.

It'd help people looking at this project have an idea of what it can do without going through the work of settings it up (which can throw people off pretty quickly).

**Comment by ywmaa** [comment]
yeah, a good idea, I always forget to do it.

**Comment by ywmaa** [comment]
I added a preview that links to youtube video when clicked on.
is it good enough ?

**Comment by SSebigo** [comment]
It's perfect, better than what I had in mind.
