### ISSUE TITLE
404 when installing from Godot 4.0 Asset Library

### ISSUE THREAD

**Issue by ConnorL33t** [ywmaa/Advanced-Movement-System-Godot#29]
![404Error](https://user-images.githubusercontent.com/19913790/222324958-6afbb307-e353-42f2-b0c8-15191959907c.PNG)

Not sure if this is due to your listing or an issue with the editor, but I was able to install other templates successfully from the asset library, so I figured I would raise the issue in your repo.

**Comment by ywmaa** [comment]
I will look at it asap.

**Comment by ywmaa** [comment]
I forgot to include the "project.godot" file for Godot Asset library.
I edited it, but it is waiting for approval from asset library managers.
I will tell you once it is fixed.

**Comment by ywmaa** [comment]
it should be fixed now, I tested it.
reopen if there is still a problem.
