### ISSUE TITLE
Long sliding deacceleration

### ISSUE THREAD

**Issue by furasesa** [ywmaa/Advanced-Movement-System-Godot#31]
Some issues I found :
1. Long sliding after keyboard release. Increasing 'deacceleration value' up to 1000 has no effect
2. Rarely produce null animation on movement 00:21
3. Crouch animation becoming jump without linear velocity.

https://github.com/ywmaa/Advanced-Movement-System-Godot/assets/16588932/5cef8da5-899a-4879-bb9f-877dc5457e8a

**Step I use**
1. Clone from master branch the date I write (0.9). It tested under **godot 4.0.3-stable** and **4.1.2-custom**
2. using **WASD** keyboard for movement, **Shift** to run, **Shift** again to sprint. See video above

**Comment by ywmaa** [comment]
Thank you for your input, 

I will check the last two issues myself.

For the sliding problem, are you using RigidBody3D or CharacterBody3D ?

**Comment by ywmaa** [comment]
I fixed 2 & 3, please check out latest commit.

also I can't really reproduce the very long sliding that happens for you.

**Comment by ywmaa** [comment]
To be sure that you change the deacceleration, change the value in CharacterMovementComponent, not the KinematicPlayer3D.

Closing this issue for now.

Reopen if issues still exist.
