### ISSUE TITLE
Crouching leads to falling animation/player's y position higher

### ISSUE THREAD

**Issue by TheFunnyBrain** [ywmaa/Advanced-Movement-System-Godot#32]
# The issue:
Player seems to increase in y-position when the ctrl key for crouching is pressed.

# Version 
- Godot 4.1.1.stable.mono.official [bd6af8e0e]
- AMSG 0.9

## Notes
- It's possible that this is because the character's height decreases when crouched, and gravity isn't catching up, but I've not read the source code yet.

- I noticed that I can press crouch when jumping, and my height increases, and that sometimes the crouched walking does work, but my player is floating in the air until I uncrouch.

[Here are a few minutes of video](https://youtu.be/cn5SgL_KSMs) in case it helps to diagnose the issue.

I'd love to help and possibly try to share a fix if I can. :) Thanks for making this fantastic system.

**Comment by TheFunnyBrain** [comment]
I am mostly prodding at it as I'm a complete Godot novice, but thought I'd share some findings:

I found that cranking the Raycast 3D's target position -20f on the y led to the player not using gravity, but meant the crouch animations working flawlessly as the player was now considered grounded.

Definitely room for improvement, but setting GroundCheck's transform.y to 1.186f and targetPosition.y to -1.4 works for me. It looks a little strange, with the character's foot clipping and small camera glitch, but it is hopefully a clue or partial solution. :)

![image](https://github.com/ywmaa/Advanced-Movement-System-Godot/assets/32782486/d730f728-0156-40ab-9623-f421ed0d03b0)

**Comment by ywmaa** [comment]
I guess you are using the RigidBody3D setup that I made it default.

and maybe the raycast doesn't touch the ground so it registers and uses the crouch animation.

**Comment by ywmaa** [comment]
I just pushed a commit to fix this bug, please check it out.

**Comment by ywmaa** [comment]
if you are curious I just had to update the groundcheck raycast height :

```
	if stance == Global.stance.crouching:
		ground_check.position.y = 0.7
		collision_shape_ref.shape.height -= crouch_switch_speed * delta /2			collision_shape_ref.shape.height -= crouch_switch_speed * delta /2
		mesh_ref.transform.origin.y += crouch_switch_speed * delta /1.5			mesh_ref.transform.origin.y += crouch_switch_speed * delta /1.5
	elif stance == Global.stance.standing and not head_bonked:		elif stance == Global.stance.standing and not head_bonked:
		ground_check.position.y = 0.186
		collision_shape_ref.shape.height += crouch_switch_speed * delta /2			collision_shape_ref.shape.height += crouch_switch_speed * delta /2
		mesh_ref.transform.origin.y -= crouch_switch_speed * delta /1.5			mesh_ref.transform.origin.y -= crouch_switch_speed * delta /1.5
```

**Comment by ywmaa** [comment]
Never Mind, I just found how to match Raycast with the capsule, very simple actually :

`ground_check.position.y = -(collision_shape_ref.shape.height/2)+collision_shape_ref.position.y + 0.2#Just a small margin`

**Comment by ywmaa** [comment]
Closing as Completed!

**Comment by TheFunnyBrain** [comment]
That's fantastic! :) Sorry I've been a little slow replying - that makes a load of sense, I initially was playing about with the mesh_ref.transform.origin.y, but couldn't find a way to make it work - that makes so much more sense than my poking! :)

Thank you :) I'd love to try and contribute code if I'm ever good enough (I'm Unity trained and making the jump, so it might be a while) :)
